### ISSUE TITLE
Update this for Swift 3?

### ISSUE THREAD

**Issue by antoniomedrano** [andrewcbancroft/SwiftSlideAnimation#1]
Any chance you want to update this for Swift 3?

**Comment by andrewcbancroft** [comment]
Absolutely one of my goals! I'm working on wrapping up a project - should be done by early March. Once I finish that, I'm planning to circle back around to my blog and my GitHub repos to update for Swift 3.

**Comment by andrewcbancroft** [comment]
Thanks a ton for your PR - I _finally_ got a chance to jump back in here and look at it.  I appreciate you taking the time to contribute!
